apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest # Imagem oficial do Apache HTTP Server
        ports:
        - containerPort: 80
      tolerations: # Aqui está a tolerância
      - key: "hardware"
        operator: "Equal"
        value: "high"
        effect: "NoSchedule"